# Generated by Django 4.0.2 on 2022-09-23 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0002_product_image_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_address', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saleapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('discount', models.DecimalField(decimal_places=1, max_digits=3)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saleapp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saleapp.product')),
            ],
        ),
    ]
