# Generated by Django 4.0.2 on 2022-10-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0003_order_orderdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('InProcess', 'InProcess'), ('Success', 'Success')], max_length=30)),
            ],
        ),
    ]
