# Generated by Django 4.0.2 on 2022-10-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0004_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('InProcess', 'InProcess'), ('Success', 'Success')], default=2, max_length=50),
            preserve_default=False,
        ),
    ]
