# Generated by Django 4.0.2 on 2022-10-08 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0005_delete_status_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ToReceive', 'ToReceive'), ('Completed', 'Completed')], max_length=50),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ToReceive', 'ToReceive'), ('Completed', 'Completed')], max_length=30)),
                ('payment_method', models.CharField(choices=[('Momo', 'Momo'), ('COD', 'COD')], max_length=30)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='saleapp.order')),
            ],
        ),
    ]
