# Generated by Django 4.0.2 on 2022-10-08 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0006_alter_order_status_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
