# Generated by Django 4.0.2 on 2022-10-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0007_remove_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Shipper', 'Shipper')], default=2, max_length=50),
            preserve_default=False,
        ),
    ]
