# Generated by Django 4.0.2 on 2022-10-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0009_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
