# Generated by Django 4.0.2 on 2022-10-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0014_alter_order_customer_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='price',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
