# Generated by Django 4.0.2 on 2022-10-26 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0015_orderdetail_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
